### PR TITLE
Apache license

### PR DESCRIPTION
**Pull request by ghost**
Added, that all further work on this project us licensed under the Apache license, project maintainers can change that. For it ti apply, EVERY CONTRIBUTOR has to agree (license change, that's what I added the clause to require only the project maintainers yes)

### CODE REVIEW

**Comment by necropotame** [comment]
Why ?

**Comment by Henningstone** [comment]
Hmm I doubt that this is so good...

**Comment by ghost** [comment]
Cause if this project grows (and I think it will) it will provide the base of many mods and a proper license would be good (and the possibility of changing that as time passes, without needing permission of EVERYONE)

**Comment by H-M-H** [comment]
I would rather go for gpl as I do not like closed source mods.

Edit: agpl would be even better for this project.

**Comment by Henningstone** [comment]
So do I, my "doubts" were about the licence itself, not about licensing. Why did you choose Apache2?

**Comment by necropotame** [comment]
Same for me. Why this one ?

**Comment by H-M-H** [comment]
So you @necropotame @Henningstone would rather go for http://www.gnu.org/licenses/agpl-3.0.html or http://www.gnu.org/licenses/gpl-3.0.html too ?

**Comment by abck** [comment]
please no license that forces modders that dont want to share source/binary
to do so (servermod). NO ONE is going to use ModAPI.

2016-01-03 23:57 GMT+01:00 H-M-H notifications@github.com:

**Comment by H-M-H** [comment]
I doubt that no one would use ModAPI then I mean just have a look at how many people give us access to their teeworlds mods (https://github.com/teeworlds/teeworlds/network/members). Additionally most popular mods are opensource as well.

**Comment by abck** [comment]
mods with accounts (citys, save, levels etc.) could not be done.
and these mods are actually the mods that could benefit most from ModAPI.

**Comment by H-M-H** [comment]
umm they surely could be done, they would simply be no longer limited to one person.

**Comment by ghost** [comment]
Sorry for a late answer. I think choosing a license with copyleft, ANY kind of copyleft would be the wrong step because it actually prevents people from modding. I would trust the community that they make mods opensource and not force them to do so. Apache says that you can do basically everything, but the AGPL/GPL is almost the same except the copyleft. And the step of adding a license for everything contributed here gives the project freedom (they could accept pr from everyone without thinking that this maybe bad because they (pr submitter) hold rights.

I think the main discussion is whether copyleft or not

**Comment by necropotame** [comment]
Ok, I'm convinced with Apache. I think we don't have to force licence for other. ModAPI is just a modification of a game. So we talk about forcing the licence of a modification of a modification of a game :-p (b.t.w., I'm for the GPL in general, this is a particular case)
For now, only me, Henningstone and killa contribute to the code (correct me if I'm wrong). So we can "officially" accept the new licence after all of us accept it. Just write "I accept the Apache licence for ModAPI", and I will merge this PR.

I accept the Apache licence for ModAPI

PS: we can still discuss it if you want.

**Comment by Henningstone** [comment]
There is another problem, what about the NetGUI code? I certainly don't want it to be licensed under Apache2, so it would be good if there would be a note that this is still licensed under my own license. (Can be found [here](https://github.com/Henningstone/tw_netgui/blob/master/license.txt#L37-L40), I reserve the right to change it at any time)

**Comment by H-M-H** [comment]
The reason why I proposed GPL/AGPL is that I want to avoid situations like this: https://github.com/fstd/teeworlds/blob/openfng/readme.txt#L16-L27
https://www.teeworlds.com/forum/viewtopic.php?pid=105190#p105190

Btw I still do not see why copyleft would prevent people from modding.

**Comment by necropotame** [comment]
@Henningstone: The licence of NetGUI says that you don't care about open source, you just care about credits. But you did it in a irritating way such that we can't even remove your example file because you put your name inside ("you are not allowed to remove my name from the files I added").

@H-M-H: If you hardcode parameters for your server, you have to share the code. It's a bit too much for me. But it's hard for me to evaluate which one (GPL or Apache) is the most compatible with the TW community.

**Comment by killaTW** [comment]
I would accept the Apache licence for ModAPI

**Comment by ghost** [comment]
@Henningstone 
Contributors claim no right at all on their work, except the right to be named in a contributors file.
If that is not enough, please move netgui source into a separate directory (only by you) and add your name at top like

```
Written by Henningstone. 
You may not delete this notice
```

And we could add that the source in the netgui directory has another license note. 

@necropotame you are right, only you three have to accept that license change, that's why it is important to evaluate the best license for the project as soon as possible (and if this changes, the project maintainers clause can be applied)

**Comment by necropotame** [comment]
The README already state that the GUI part is BASED on NetGUI. But the code must be well integrated to ModAPI. It's not possible to keep specific licence, or to keep names of some part of ModAPI. Henningstone contribute to ModAPI by implementing the GUI part. But it's no more "NetGUI". It will be probably no more compatible with the protocol of NetGUI.

**Comment by Henningstone** [comment]
That is right, it won't be compatible at some point of time anymore, because I want to also make use of some ModAPI features for it. When thinking about it, you are right, let's say the GUI thingy here is mod of NetGUI ("based on it"), but is _not_ NetGUI anymore. With this being said, I can keep my own licence on it, and the code used here can be licensed under some other license.

**Comment by necropotame** [comment]
Good, so the last thing to decide is between Apache or GPL/AGPL. But it's still unclear for me which part of the code will be under that licence. Since ModAPI is more or less an API/library, some part of a mod can be called "modification of ModAPI", but some other parts are just "use of ModAPI". In particular, I want to introduce a new folder, src/mod, that should contains the part done by the modder. This folder will not really be a part of TW/ModAPI. Choose GPL means more or less "All creations made by our software must be under GPL licence".

For TW/ModAPI, I agree that the licence must be GPL. But for the src/mod folder, Apache could be enough. What do you think ?

**Comment by ghost** [comment]
Basically we are talking about our modification. Our implementation of this library, if we choose a license with copyleft but teeworlds doesn't have one (oh wow) many modder may stick to standard teeworlds because they don't want to make their code available (or from the beginning of their mod avaliable). If teeworlds changes to gpl, we have to do the same, cause of the copyleft. But I think Apache is the right license because this license is more about giving contributions to the project (not the contributors), and not about what license others should use. 
@necropotame @killaTW you did accept the license. 
@Henningstone you too? Just write "I accept the Apache licence for ModAPI" and I will accept the pr (necropotame)

**Comment by Henningstone** [comment]
"I accept the Apache licence for ModAPI."

~~You can merge it.~~ // EDIT: Well, then don't merge it :stuck_out_tongue:

**Comment by Schwertspize** [comment]
Do not merge! I have to refactor a bit

**Comment by ghost** [comment]
git diff is a bit confusing but if you look at the whole file im fine.

you can merge now

**Comment by necropotame** [comment]
Finally, I can merge this PR :-D Thanks!

**Pull request merged**
