### PR TITLE
mod download bar

### PR DESCRIPTION
**Pull request by killaTW**

### CODE REVIEW

**Comment by Henningstone** [comment]
You may want to rebase it before it gets merged...

**Comment by necropotame** [comment]
Did you test it ?

**Comment by Henningstone** [comment]
I did. It does what it's supposed to do ^^ The download bar shows up if the mod is not present, and it displays the value correctly. Ready to merge I'd say, but I highly recommend @killaTW rebasing it first.

**Comment by necropotame** [comment]
What is rebasing ? ^^

**Comment by Henningstone** [comment]
That. Is rebasing. ^^

**Pull request merged**
