### PR TITLE
Mod directory to fix #23

### LINKED ISSUE #23: Add src/mod directory
This directory must contains files modified by moders, like src/game/server/gametypes/mod.cpp. In theory, moders must avoid editing other folders. This means that we must provide more virtual functions and classes to allows modification of the game.

### PR DESCRIPTION
**Pull request by necropotame**

### CODE REVIEW

**Comment by Henningstone** [comment]
You definitely go better if you rebase that. The last three commits are just garbage…

**Comment by necropotame** [comment]
Like I said in #23 ^^
What I need to understand by your cat-like smiley ? :-p

**Comment by Henningstone** [comment]
"cat-like smiley" == "minor style issue" :wink:

**Comment by necropotame** [comment]
I failed again. The multisnapshot merge was between two commits related to this PR and disappear with my "git reset" thing.

**Comment by Henningstone** [comment]
You mean git rebase? Then you did something wrong... I should have a local copy of it left, let me see...

**Comment by necropotame** [comment]
No I mean reset, to remove all commits that I've made and then group them in a new commit. It's like if I don't have merged this branch with the multisnapshot branch, but did all modification again (that's the mistake). If I manually merge this branch (and fix conflicts) to the master, then the master will contain a new commit called "Move mod-related code in ./src/mod directory to fix #23". It's what we want, no ?

Edit: I've done it on my computer, so I just need to push it. Master will get only one new entry : "Move mod-related code in ./src/mod directory to fix #23". Tell me that you accept this PR, and I will push it.

**Comment by Henningstone** [comment]
> No I mean reset, to remove all commits that I've made and then group them in a new commit

I think that reset is not the thing to be used for this, and therefore you got things messy. "git rebase" puts all the commits you want together into one commit which does the changes that would have been done by your 4 commits (so 'commit -> revert' makes 'nothing changes'). But that is not the matter right now.

I am fine if you merge it, push to master and close the PR :smile:

**Comment by ghost** [comment]
normally reset is easier...

**Pull request closed without merging**
