### PR TITLE
various fixes which made compiling on macOS possible

### PR DESCRIPTION
**Pull request by H-M-H**
- added c++11 for clang as this allows things like: `sizeof(class::member)`
  see http://stackoverflow.com/questions/29359661/clang-error-invalid-use-of-non-static-data-member for more. On macOS libc++ should be used as it is more up to date,
  however, this required to increase the minimum version for mac to 10.7.
- fixed bam.lua which now does not ignore setting `compiler.driver = 'clang'` in config.lua .
- make sure all calls to GetAssetCatalog are aware of template-specializations
  funfact: compiling with clang in debug mode works nicely but in release-mode the
  specializations of GetAssetCatalog will not be called which results in a runtime error as the
  generic GetAssetCatalog is called and returns a nullpointer. Apparently invoking clang++ with
  -O2 which bam does in release mode but not in debug mode does not make the
  specializations of GetAssetCatalog available to some invokations. For more see:
  http://stackoverflow.com/questions/59331/visibility-of-template-specialization-of-c-function
  http://stackoverflow.com/questions/2498435/declaration-of-template-class-member-specialization
- fixed downcasting of int to bool in GetClientProtocol
- removed some whitespaces (well, actually my editor did :P)

### CODE REVIEW

**Comment by H-M-H** [comment]
For a nicer diff without all the whitespaces see: https://github.com/teeuniverses/teeuniverses/pull/97/files?w=1

**Comment by necropotame** [comment]
I'm completely sorry, I've missed this pull request. I will try to merge it

**Comment by H-M-H** [comment]
I already wondered why I got no response so far. Too bad that there are conflicts for merging now. I guess I will have a look at this soon and try to resolve those conflicts.

**Comment by necropotame** [comment]
Again, I'm sorry. It's because I though is was a push request for TeeWorlds since I didn't expected that someone want to try TeeUniverses now :P Since it's my fault, I will try to do it next week.

**Pull request merged**
