### PR TITLE
First draft for weapon

### PR DESCRIPTION
**Pull request by necropotame**
Lets reverse the roles. You have to review my code and push the merge button to merge this draft to the weapon branch. This is the first step for #26.

In this draft, all weapons mechanics are in a CModAPI_Weapon class instead of in the CCharacter class. Each weapon must implement a different class that inherit CModAPI_Weapon. To add a new type of weapon, you have to create your own CModAPI_Weapon_XXXXX and add an enum. So you don't have to change the character.cpp file. I've tested it without enemies and it seems to work.

The next step will be the graphics to show different sprite and animation demanding of the weapon ID.

### CODE REVIEW

**Comment by Henningstone** [comment]
Is it ok if I change some things myself (because it is pretty much) and then just push it into this PR after you had a look at it (in my fork)?

**Comment by necropotame** [comment]
No problem, you can do it :-)

**Comment by necropotame** [comment]
Can create a PR from your branch to this one? It will be convenient to compare and discuss it.

**Comment by Henningstone** [comment]
Can directly push my commit into this pr ;)

**Comment by necropotame** [comment]
I can't. Can you do it ?

**Comment by Henningstone** [comment]
I already did it: https://github.com/teeworlds-modapi/teeworlds/pull/47/commits
That was what I meant by my above comment :/

**Comment by necropotame** [comment]
OK!

**Comment by ghost** [comment]
Necropotame you can push by pushing to the branch. Henningstone cam because he is collaborator. But btw I would not add him as collaborator, instead add him to your organisation; https://github.com/teeworlds-modapi that would be better.

**Pull request merged**
