### PR TITLE
Multisnapshot draft

### PR DESCRIPTION
**Pull request by necropotame**
Multisnapshot system (#8). Each entity implements Snap07() and Snap07ModAPI(). Depending of the client protocol, the 0.7 or 0.7 ModAPI snapshot is send. Each snapshot use different SnapID, so they are really independent.

Since all actual entities behaves similarly in 0.7 and 0.7 ModAPI, I've added CModAPI_EntitySnapshot07 that allow to define only a Snap() function, reused in both Snap07() and Snap07ModAPI(), but taking care of the difference of SnapID.

(the changelog is a mess because multisnapshot was not up to date, sorry)

### CODE REVIEW

**Comment by killaTW** [comment]
Maybe u should rebase this

**Comment by necropotame** [comment]
I've updated the multisnapshot branch. Is it enough ?

**Comment by killaTW** [comment]
U never free the memory of m_IDList in entity.cpp or?

**Comment by necropotame** [comment]
m_IDList is an TW array. The memory is free in the destructor of array(). The IDs inside m_IDList are free in the destructor of CModAPI_EntitySnapshot07 (line 22)

**Comment by killaTW** [comment]
Oh sry

**Comment by necropotame** [comment]
I think we can merge it directly in the master branch. Missing part are just new features, so more or less independent of this code.

**Comment by ghost** [comment]
manually merged directly into master. also rebased these commits. sounds good to me (revert button doesnt work but we CAN if its that damn bad)
(github doesnt count that, im sorry)

**Pull request closed without merging**
